/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Event;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-03-21T17:25:50.041Z")

@Api(value = "event", description = "the event API")
public interface EventApi {

    @ApiOperation(value = "Create an event", nickname = "createEvent", notes = "Create an event for Beevy", tags={ "event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created event"),
        @ApiResponse(code = 405, message = "Failed to create event") })
    @RequestMapping(value = "/event/create",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> createEvent(@ApiParam(value = "Event Object" ,required=true )  @Valid @RequestBody Event body);


    @ApiOperation(value = "Get all events that are available", nickname = "getEvents", notes = "Get Events", response = Event.class, responseContainer = "List", tags={ "event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Event.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Failed to get events") })
    @RequestMapping(value = "/event",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Event>> getEvents();

}
