swagger: '2.0'
info:
  description: Server to manage events for Beevy
  version: 1.0.0
  title: Beevy App
tags:
  - name: event
    description: Create and get events
parameters:
  userID:
    name: userID
    in: path
    description: ID of a User
    required: true
    type: string
  username:
    name: username
    in: path
    description: username
    required: true
    type: string
paths:
  /user:
    post:
      tags:
        - user
      summary:  Create user if not existent
      description: Create user if not existent
      operationId: createUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User Object
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: Created user
        '405':
          description: Failed to create user
  /user/{username}/{userID}:
    parameters:
      - $ref: '#/parameters/username'
      - $ref: '#/parameters/userID'
    get:
      tags:
        - user
      summary: Return security token for a user
      description: Get security token
      operationId: getUserToken
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: string
        '404':
          description: User not found
  /event:
    get:
      tags:
        - event
      summary: Get all events that are available
      description: Get Events
      operationId: getEvents
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Event'
        '400':
          description: Failed to get events
  /event/create:
    post:
      tags:
        - event
      summary: Create an event
      description: Create an event for Beevy
      operationId: createEvent
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Event Object
          schema:
            $ref: '#/definitions/Event'
      responses:
        '201':
          description: Created event
        '401':
          description: Unauthorized
        '405':
          description: Failed to create event
  /event/join:
      post:
        tags:
          - event
        summary: Join an event
        description: Join an existing event
        operationId: joinEvent
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - in: body
            name: body
            description: Join Event Data
            schema:
              $ref: '#/definitions/JoinEventData'
        responses:
          '201':
            description: Joined event
          '405':
            description: Failed to join event
definitions:
  Event:
    type: object
    properties:
      eventID:
        type: string
      admin:
        $ref: '#/definitions/User'
      title:
        type: string
      summary:
        type: string
      description:
        type: string
      type:
        type: string
        enum:
          - event
          - project
      date:
        type: string
      endDate:
        type: string
      address:
        $ref: '#/definitions/Address'
      registeredMembers:
        type: array
        items:
          type: string
      possibleMemberCount:
        type: integer
      currentMemberCount:
        type: integer
  Address:
    type: object
    properties:
      street:
        type: string
      zip:
        type: integer
      city:
        type: string
  User:
    type: object
    properties:
      username:
        type: string
      userID:
        type: string
      mail:
        type: string
      token:
        type: string
  JoinEventData:
    type: object
    properties:
      userID:
        type: string
      token:
        type: string
      eventID:
        type: string